@echo off
Rmdir .nuget\packages\ /s /q
NuGet.exe install MSBuildTasks        -OutputDirectory .nuget\packages\ -NonInteractive -Version 1.5.0.235
NuGet.exe install NUnit               -OutputDirectory .nuget\packages\ -NonInteractive -Version 3.14.0
NuGet.exe install NUnit.ConsoleRunner -OutputDirectory .nuget\packages\ -NonInteractive -Version 3.17.0
NuGet.exe install Microsoft.Build -OutputDirectory .nuget\packages\ -NonInteractive -Version 14.3.0
NuGet.exe install Microsoft.Build.Framework -OutputDirectory .nuget\packages\ -NonInteractive -Version 14.3.0
NuGet.exe install Microsoft.Build.Tasks.Core -OutputDirectory .nuget\packages\ -NonInteractive -Version 14.3.0
NuGet.exe install Microsoft.Build.Utilities.Core -OutputDirectory .nuget\packages\ -NonInteractive -Version 14.3.0
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference = 'Stop'; $pkgId = 'WixToolset.Sdk'; $pkgIdLower = $pkgId.ToLowerInvariant(); $pkgVersion = '4.0.6'; $pkgFolder = Join-Path '.nuget\packages' ($pkgId + '.' + $pkgVersion); $pkgFile = Join-Path '.nuget\packages' ($pkgId + '.' + $pkgVersion + '.nupkg'); Invoke-WebRequest -UseBasicParsing -Uri ('https://api.nuget.org/v3-flatcontainer/' + $pkgIdLower + '/' + $pkgVersion + '/' + $pkgIdLower + '.' + $pkgVersion + '.nupkg') -OutFile $pkgFile; Expand-Archive -Path $pkgFile -DestinationPath $pkgFolder -Force; $wixNormalizePathOld = '$([MSBuild]::NormalizePath($(MSBuildProjectDirectory), $(ProjectAssetsFile)))'; $wixNormalizePathNew = '$([System.IO.Path]::GetFullPath($([System.IO.Path]::Combine($(MSBuildProjectDirectory), $(ProjectAssetsFile)))))'; $wixNormalizeDirectoryOld = '$([MSBuild]::NormalizeDirectory($(MSBuildProjectDirectory), $(PdbOutputDir)))'; $wixNormalizeDirectoryNew = '$([System.String]::Concat($([System.IO.Path]::GetFullPath($([System.IO.Path]::Combine($(MSBuildProjectDirectory), $(PdbOutputDir))))), ''\''))'; $wixPropsFile = Join-Path $pkgFolder 'tools\wix.props'; (Get-Content -Raw $wixPropsFile).Replace($wixNormalizePathOld, $wixNormalizePathNew).Replace($wixNormalizeDirectoryOld, $wixNormalizeDirectoryNew) | Set-Content -NoNewline $wixPropsFile; $wixTargetsFile = Join-Path $pkgFolder 'tools\wix.targets'; (Get-Content -Raw $wixTargetsFile).Replace($wixNormalizePathOld, $wixNormalizePathNew).Replace($wixNormalizeDirectoryOld, $wixNormalizeDirectoryNew) | Set-Content -NoNewline $wixTargetsFile; $wixBuildTaskDir = Join-Path $pkgFolder 'tools\net472'; Copy-Item '.nuget\packages\Microsoft.Build.14.3.0\lib\net45\Microsoft.Build.dll' $wixBuildTaskDir -Force; Copy-Item '.nuget\packages\Microsoft.Build.Framework.14.3.0\lib\net45\Microsoft.Build.Framework.dll' $wixBuildTaskDir -Force; Copy-Item '.nuget\packages\Microsoft.Build.Tasks.Core.14.3.0\lib\net45\Microsoft.Build.Tasks.Core.dll' $wixBuildTaskDir -Force; Copy-Item '.nuget\packages\Microsoft.Build.Utilities.Core.14.3.0\lib\net45\Microsoft.Build.Utilities.Core.dll' $wixBuildTaskDir -Force; Remove-Item -Path $pkgFile -Force"
